### ISSUE TITLE
Currently unable to run tests

### ISSUE THREAD

**Issue by phildini** [pybee/ouroboros#12]
When I try to `python setup.py test`, I get the following:

```
SensitiveDependence:ouroboros phildini$ python setup.py test
running test
running egg_info
creating ouroboros.egg-info
writing ouroboros.egg-info/PKG-INFO
writing top-level names to ouroboros.egg-info/top_level.txt
writing dependency_links to ouroboros.egg-info/dependency_links.txt
writing manifest file 'ouroboros.egg-info/SOURCES.txt'
reading manifest file 'ouroboros.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'requirements*.txt'
writing manifest file 'ouroboros.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    test_suite='tests'
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 157, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 138, in with_project_on_sys_path
    func()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 178, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_cmath'
```

Looking in the codebase, I don't even _see_ `test_cmath` referenced anywhere, so I'm not sure what's going on.

**Comment by mmchugh** [comment]
I do see the module here: https://github.com/pybee/ouroboros/blob/master/tests/test_cmath.py

Is ouroboros supposed to run on 2.7? The tests run well for me on 3.5, but also fail on 2.7
